<?php

/** @var array $params */
return [
    'class' => 'yii\web\UrlManager',
    'hostInfo' => $params['frontendHostInfo'],
    'baseUrl' => '',
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'cache' => false,
    'rules' => [
        '' => 'site/index',
        'notification' => 'user/notificationsetting',
        'earn' => 'user/referral-earn',
        'myteam' => 'user/tree',
        'threads' => 'chat/threads',
        'messages' => 'chat/messages',
        'knowledge' => 'site/knowledge',
        'about' => 'site/about',
        'terms' => 'site/terms',
        'policy' => 'site/policy',
        'dashboard' => 'user/dashboard',
        'gallery' => 'user/gallery',
        'wallet' => 'user/wallet',
        'plan' => 'auth/signup/plan',
        'subscription' => 'user/subscription',
        'profile' => 'user/profile',
        'addtalent' => 'user/addtalent',
        'addaddress' => 'user/addaddress',
        'updateaddress' => 'user/updateaddress',
        'updateprofile' => 'user/updateprofile',
        'square/details' => 'auth/square/payment-form',
        'orders' => 'cabinet/order',
        'sales' => 'cabinet/sales',
        'products' => 'shop/product/index',
        'addproduct' => 'shop/product/create',
        'contact' => 'contact/index',
        'cart' => 'shop/cart/index',
        'signup' => 'auth/signup/plan',
        'selectplan' => 'auth/signup/selectplan',
        'signup/<_a:[\w-]+>' => 'auth/signup/<_a>',
        '<_a:login|logout>' => 'auth/auth/<_a>',
        'blog' => 'blog/post/index',
        'blog/tag/<slug:[\w\-]+>' => 'blog/post/tag',
        'blog/<id:\d+>' => 'blog/post/post',
        'blog/<id:\d+>/comment' => 'blog/post/comment',
        'blog/<slug:[\w\-]+>' => 'blog/post/category',
        'catalog' => 'shop/catalog/index',
        // ['class' => 'frontend\urls\CategoryUrlRule'],
        'catalog/<id:\d+>' => 'shop/catalog/product',
        'catalog/category/<id:\d+>' => 'shop/catalog/category',
        'catalog/brand/<id:\d+>' => 'shop/catalog/brand',
        'catalog/search' => 'shop/catalog/search-product-by',
        'cabinet' => 'cabinet/default/index',
        'cabinet/<_c:[\w\-]+>' => 'cabinet/<_c>/index',
        'cabinet/<_c:[\w\-]+>/<id:\d+>' => 'cabinet/<_c>/view',
        'cabinet/<_c:[\w\-]+>/<_a:[\w-]+>' => 'cabinet/<_c>/<_a>',
        'cabinet/<_c:[\w\-]+>/<id:\d+>/<_a:[\w\-]+>' => 'cabinet/<_c>/<_a>',
        ['class' => 'frontend\urls\PageUrlRule'],
        '<_c:[\w\-]+>' => '<_c>/index',
        '<_c:[\w\-]+>/<id:\d+>' => '<_c>/view',
        '<_c:[\w\-]+>/<_a:[\w-]+>' => '<_c>/<_a>',
        '<_c:[\w\-]+>/<id:\d+>/<_a:[\w\-]+>' => '<_c>/<_a>',
    ],
];
